language: java
cache:
  directories:
    - $HOME/.m2
script:
  - set -e
  - mvn clean install --errors --batch-mode --quiet
  - mvn clean --quiet
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - oraclejdk8
